name: 延期记录
description: 任务延期时创建
type: "Delay"
title: "[Delay] "
body:
  - type: dropdown
    id: delay-reason
    attributes:
      label: 延期原因分类
      options:
        - 个人原因
        - 紧急需求插入
        - 紧急Bug插入
        - 估时不准
        - 外部依赖阻塞
        - 需求变更
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 延期原因
      placeholder: 说明延期原因
    validations:
      required: true

  - type: input
    id: new_date
    attributes:
      label: 新目标日期
      placeholder: "例：2026-03-20"
    validations:
      required: true
